# Generated by Django 3.0.5 on 2020-05-02 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_textbubble_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.URLField(max_length=800)),
                ('bubble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.TextBubble')),
            ],
        ),
    ]
