# Generated by Django 3.0.5 on 2020-05-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200502_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.AddField(
            model_name='textbubble',
            name='links',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
