# Generated by Django 3.0.5 on 2020-05-05 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20200505_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='pdf',
            new_name='pdf_link',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='name',
            new_name='pdf_name',
        ),
    ]
