# Generated by Django 3.0.5 on 2020-05-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20200505_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='pdf_link',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
