# Generated by Django 3.0.5 on 2020-05-06 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_auto_20200506_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='language_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llink', to='portfolio.TextBubble'),
        ),
    ]
